# Generated by Django 4.2.7 on 2025-05-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[('1', 'Low'), ('2', 'Normal'), ('3', 'High'), ('4', 'Critical')], default='2'),
        ),
    ]
